#include "graph_link.h"

void modify_map(GraphLink* g, map<FuncLine,int>* cntmap){
	FuncLine FL;
	FL.name = (char*)"getgrade";FL.line = 3;
	cntmap->insert(std::map<FuncLine, int>::value_type (FL, 2));
	FL.name = (char*)"getgrade";FL.line = 5;
	cntmap->insert(std::map<FuncLine, int>::value_type (FL, 2));
	FL.name = (char*)"getgrade";FL.line = 6;
	cntmap->insert(std::map<FuncLine, int>::value_type (FL, 0));
	FL.name = (char*)"getgrade";FL.line = 7;
	cntmap->insert(std::map<FuncLine, int>::value_type (FL, 2));
	FL.name = (char*)"getgrade";FL.line = 8;
	cntmap->insert(std::map<FuncLine, int>::value_type (FL, 0));
	FL.name = (char*)"getgrade";FL.line = 9;
	cntmap->insert(std::map<FuncLine, int>::value_type (FL, 2));
	FL.name = (char*)"getgrade";FL.line = 10;
	cntmap->insert(std::map<FuncLine, int>::value_type (FL, 0));
	FL.name = (char*)"getgrade";FL.line = 11;
	cntmap->insert(std::map<FuncLine, int>::value_type (FL, 2));
	FL.name = (char*)"getgrade";FL.line = 12;
	cntmap->insert(std::map<FuncLine, int>::value_type (FL, 0));
	FL.name = (char*)"getgrade";FL.line = 13;
	cntmap->insert(std::map<FuncLine, int>::value_type (FL, 2));
	FL.name = (char*)"getgrade";FL.line = 14;
	cntmap->insert(std::map<FuncLine, int>::value_type (FL, 2));
	FL.name = (char*)"getgrade";FL.line = 15;
	cntmap->insert(std::map<FuncLine, int>::value_type (FL, 0));
	FL.name = (char*)"getgrade";FL.line = 16;
	cntmap->insert(std::map<FuncLine, int>::value_type (FL, 2));
	FL.name = (char*)"main";FL.line = 18;
	cntmap->insert(std::map<FuncLine, int>::value_type (FL, 2));
	FL.name = (char*)"main";FL.line = 22;
	cntmap->insert(std::map<FuncLine, int>::value_type (FL, 2));
	FL.name = (char*)"main";FL.line = 23;
	cntmap->insert(std::map<FuncLine, int>::value_type (FL, 2));
	FL.name = (char*)"main";FL.line = 28;
	cntmap->insert(std::map<FuncLine, int>::value_type (FL, 2));
	modify_visit(g,(char*)"getgrade", 3);
	modify_visit(g,(char*)"getgrade", 5);
	modify_visit(g,(char*)"getgrade", 7);
	modify_visit(g,(char*)"getgrade", 9);
	modify_visit(g,(char*)"getgrade", 11);
	modify_visit(g,(char*)"getgrade", 13);
	modify_visit(g,(char*)"getgrade", 14);
	modify_visit(g,(char*)"getgrade", 15);
	modify_visit(g,(char*)"getgrade", 16);
	modify_visit(g,(char*)"main", 18);
	modify_visit(g,(char*)"main", 22);
	modify_visit(g,(char*)"main", 23);
	modify_visit(g,(char*)"main", 28);
}
